### ISSUE TITLE
Add style guide / pattern for Blue status highlights  to DS

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#388] opened 2021-01-22 19:13 UTC
## Issue Description
Add style guide / pattern fo Blue status highlights to DS

---
## Tasks
- [ ] Audit of current use
- [ ] Update Sketch file
- [ ] Document
- [ ] Add to design.va.gov

## Acceptance Criteria
- [ ] Updates Sketch file
- [ ] Accessible on design.va.gov
---

**Comment by caw310** [comment] 2021-11-10 18:59
@GnatalieH , let's break this down further once you've identified what this entails.

**Comment by GnatalieH** [comment] 2021-11-15 16:42
@caw310 this work is cards-related and will be handled in #[572](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/572). Can I close it?

**Comment by caw310** [comment] 2021-11-15 16:48
@GnatalieH sure, can close this and just link this to 572.

**Comment by GnatalieH** [comment] 2021-11-16 14:47
Closing as duplicate of #572.

**Closed by GnatalieH** 2021-11-16 14:47 UTC
Labels: vsp-design-system-team
