### ISSUE TITLE
Create pattern for content/statuses on cards in DS

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/vets-design-system-documentation#387] opened 2021-01-22 19:14 UTC
## Issue Description
Create pattern for  "statuses" on cards in DS

---
## Tasks
- [ ] Audit of current use
- [ ] Update Sketch file
- [ ] Document
- [ ] Add to design.va.gov

## Acceptance Criteria
- [ ] Updates Sketch file
- [ ] Accessible on design.va.gov
---

**Comment by GnatalieH** [comment] 2021-11-23 18:56
I think this ticket can be closed because it's a duplicate of #572. The status element will be covered in the general Cards pattern.

**Closed by GnatalieH** 2021-11-23 18:56 UTC
Labels: vsp-design-system-team
