### ISSUE TITLE
va-number-input "currency" option does not work with "uswds" (v3 components)

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#2106] opened 2023-09-18 20:05 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

If you try to provide the currency option to a va-number-input with uswds, nothing happens

## What I expected to happen

Expect the currency option to work

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

Provide the currency option to a va-number-input with uswds, nothing happens. Also see storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-number-input--default

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment] 2023-09-19 17:22
This was intentional. We plan to support the [USWDS input prefix and suffix](https://designsystem.digital.gov/components/input-prefix-suffix/) on a number of fields. We'll be adding that later. Is this used in a form that your team is working on?

**Comment by humancompanion-usds** [comment] 2023-09-19 17:23
In fact, Carol beat you to the punch. This is a duplicate of issue #2105

**Closed by humancompanion-usds** 2023-09-19 17:23 UTC
Labels: bug, platform-design-system-team
