### ISSUE TITLE
[Bug] Character count visibility

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2469] opened 2024-02-02 16:45 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

However, I think this [commit is connected to his issue](https://github.com/department-of-veterans-affairs/component-library/commit/ae95cdfcfcdaadc6fa2711767202d7b8c6cffe47).

## What happened

Yesterday I noticed character limits were appearing on name fields in a form, and today I further noticed that they are showing on address fields. I checked all simple forms using our v3 pattern, and I checked additional non-simple forms that also use our patterns and this is showing up in those forms on staging *and* production.

This behavior was surprising and unexpected to us. As we don't think the character limits need to be revealed at all times - especially on name fields. 

[VA Form 40-0247](https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247/introduction)
<img width="420" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/a6fa8804-6b74-4f44-bbe3-000392bfc991">

[VA Form 20-10206](https://staging.va.gov/records/request-personal-records-form-20-10206/phone-email)
<img width="420" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/88ded18c-7330-46f7-b21d-fa247c868629">

[VA Form 21-0966](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/veteran-personal-information)
<img width="420" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/6e325fd6-a718-4445-87dd-2f5a8bc8a8c9">

## What I expected to happen

I expected to be able to control when the character count limitations appeared on a component even if limits are set.

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook) Macbook
- Browser: (e.g. Firefox, IE 11) Chrome

Steps to reproduce:

1. Navigate to https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247/introduction
2. Click "Start your request"
3. On the next page see the character limits displaying under the fields
4.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [X] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
The Accessibility community of practice talked about this in our sync this morning, and we're curious if this was intentional (forcing the display of the limitations) or if this was accidental. If it's intentional, we'd like to talk more about it and understand why.

**Comment by humancompanion-usds** [comment] 2024-02-02 19:41
This was perhaps a misunderstanding of adhering to the USWDS component where they have split out [Character Count as a distinct component](https://designsystem.digital.gov/components/character-count/) (which IMHO, it should not be). It is in fact just functionality of the text-input. However, the way USWDS has shown it here makes it seem like the character count should appear by default. It should only appear when the prop is on.

However, @Andrew565 did ask me about this:

> The 'charcount' prop requires that the 'maxlength' prop also be set. Since we're deprecating the 'Max Length' variation, should I just default the component to showing the "Character Count" variation if the 'maxlength' prop is set? This would preclude the need to specify the 'charcount' prop separately. For what it's worth, there are currently 0 instances of the "Max Length" or "Character Count" variations in use in vets-website, so there would be no changes needed there whatever we decide API-wise.

I said I thought it would be fine given that there were no instances of max length or character count. But I should have asked more questions. It sounds like we are not being clear that maxlength is an HTML attribute that is often set on form fields and that should NOT trigger character count. So I apologize. I think, once again, this should have come to a designer first to define the behavior and we keep trying to match USWDS without conversation about what that means first. Let me try to write out the rules:

* va-text-input and va-textarea should have a prop that allows for the setting of the HTML property maxlength. That should NOT turn on character count display. That's simply for enforcing a max-length. We don't always need or want to communicate that via character dcount (it creates a lot of noise).
* va-text-input and va-textarea should have a prop that allows for showing a character count that uses the maxlength value. 
* When the character count prop is true we show the "Character count" text followed by the maxlength value underneath the form element. 

**I believe what we have in va-textarea is actually already correct.** 

The problems we were trying to solve came from @rsmithadhoc's review:

> Our [Max Length](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--default#max-length) variation has some issues. So deprecating this in favor of Character Count is appropriate. 
>  * Doesn't tell you about the character count when tabbing to the field.
>  * When the character count is reached, only then does hint text pop up and get read out. If you are still typing, it may get cut off when it reads this out.

So the desire was just to show the character count if the prop was on rather than waiting to show it when the maxlength is hit. 

I believe all we need to do here now is make va-text-input match what we have in va-textarea. But I would appreciate another set of eyes on this.

**Comment by jeana-adhoc** [comment] 2024-02-03 20:39
Hi @humancompanion-usds - what you wrote makes a lot of sense.  And textarea seems to work in the way you outlined above. However, I'm not sure va-textarea is behaving _exactly_ correctly either.   On the [PA Request form](https://staging.va.gov/records/request-personal-records-form-20-10206/additional-records-information) we have a text area that has the max length defined and it is showing that as the character count but that's expected because `charcount="true"` on the component. All good. Except, I don't think the label for the charcount is correct.

<img width="420" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/6b689827-65c8-4251-83dd-4c4f91362ae6">

What's surprising though is that the text on page load is always `xxx characters left`, not `xxx characters allowed` like it is in storybook. I also noticed that in the text-input fields, the charcount label is always `characters left` not `characters allowed`.

**Comment by humancompanion-usds** [comment] 2024-02-05 14:39
@caw310  - This is impacting every form on the platform and is a regression. We need to fix this a.s.a.p. Thanks.

**Comment by caw310** [comment] 2024-02-05 15:50
Adding to current sprint as unplanned due to urgency.

**Comment by it-harrison** [comment] 2024-02-05 20:02
PR is [here](https://github.com/department-of-veterans-affairs/component-library/pull/1049)

**Comment by it-harrison** [comment] 2024-02-08 16:42
All changes to `vets-website` have been merged

**Closed** 2024-02-08 20:56 UTC
Labels: bug, platform-design-system-team, va-text-input
