### ISSUE TITLE
va-on-this-page should not render if there are no H2 articles are found

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/vets-design-system-documentation#530] opened 2021-08-24 15:53 UTC
The [va-on-this-page](va-on-this-page) component currently scans the document for `article h2` elements, and generates a table of contents for them. But it does so even if no h2 articles are found.

It should not render at all if no h2 articles are found.

**Comment by bkjohnson** [comment] 2021-08-24 21:48
I'm curious about the kinds of contexts it's being used where there are no `<h2>` elements on the page.

**Comment by mpelzsherman** [comment] 2021-08-24 21:55
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28249

**Comment by bkjohnson** [comment] 2021-08-24 22:16
It seems like that page may be violating the a11y best practice rule which says that heading levels should only increase by 1.

![image](https://user-images.githubusercontent.com/2008881/130696716-ced27350-5f5a-42ba-86da-6c7435971ce3.png)

https://dequeuniversity.com/rules/axe/3.5/heading-order

We could certainly modify the component to not render anything if it doesn't find any `<h2>`s, but I think there are other options available:

1. Don't put the element on the page if it is known that there won't be `<h2>` on the page
    - Looking at the linked issue, it looks like that checkbox could control this, or the liquid template might be able to as well.
2. Ensure that the headings go from `<h1>` to `<h2>` rather than straight to `<h3>`.


@noahgelman or @1Copenut, any thoughts?

**Comment by mpelzsherman** [comment] 2021-08-24 22:40
That's a fair point, @bkjohnson . The page content is managed by the CMS team. I'll suggest they fix their content structure, and that should address this one case, but I think this is still worth considering making the suggested change to the component.

**Comment by 1Copenut** [comment] 2021-08-25 14:48
@bkjohnson second option, to ensure headings always go from `<h1>` to `<h2>` is the right call. I know it's aspirational, but we should have no content skipping heading levels. I've been told and observed, almost to a person, that assistive tech users navigate asynchronously by heading level and have an expectation they're nested properly.

Tailoring the component to fit markup seems the wrong tack in my opinion. That's just that--an opinion--but I feel the short-term nuisance is worth the long-term improvement.

**Comment by mpelzsherman** [comment] 2021-08-25 14:58
I see this as more of a measure to protect against mistakes made by Contant editors, who are only human after all. Yes of course, we should always strive to create perfect content but in the real world that doesn’t happen and this is a fairly simple way to improve the veteran experience.

**Comment by bkjohnson** [comment] 2021-08-31 23:43
Closing for now since the component is working as intended.

**Closed by bkjohnson** 2021-08-31 23:43 UTC
Labels: vsp-design-system-team
