### ISSUE TITLE
Breadcrumb's current page styling should not remove pointer events

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/vets-design-system-documentation#1458] opened 2023-01-23 13:01 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

### The current page in the breadcrumb responds to keyboard commands

<img width="279" alt="Screen Shot 2023-01-23 at 7 24 08 AM" src="https://user-images.githubusercontent.com/14154792/214038874-e620f814-2a5e-4c92-a837-fba792ec79ce.png">

If a user were to hit `enter`, it will refresh the page.

https://user-images.githubusercontent.com/14154792/214039052-101ebfdb-b3a8-4160-9405-85ac8332d5ac.mov

### But it lacks a hand cursor on hover and does not respond on click

https://user-images.githubusercontent.com/14154792/214045045-9c5b4cb3-5dd6-459d-bc7a-677d77fc7a83.mov

[The hand cursor (which is native to links)](https://adamsilver.io/blog/buttons-shouldnt-have-a-hand-cursor/) appears on hover. However, the aria current styling removes pointer events and the hand cursor.

## What I expected to happen

[Following W3C's example, we shouldn't hide the cursor or block pointer events](https://www.w3.org/WAI/ARIA/apg/example-index/breadcrumb/index.html) as it creates an inconsistency between the keyboard and hover experience.

https://user-images.githubusercontent.com/14154792/214045410-fb856179-7aa1-4a4a-a8bc-2b9f91073fb8.mov

This can be accomplished fairly easily by simply removing:
- `pointer-events: none`
- `cursor: default`

### Some nuance

That being said, there remains to be some argument in the a11y community over whether or not the current page should (or shouldn't) be a link. That's definitely a conversation for another time, but for now, I think reaching a state of consistency between various navigation mechanisms (mouse vs. keyboard) is a solid step forward.

Steps to reproduce:

1. [View breadcrumbs on storybooks](https://design.va.gov/storybook/iframe.html?id=components-va-breadcrumbs--default&viewMode=story)
2. Tab to current page, confirm it takes focus and responds to enter
3. Hover over current page, confirm it does not show a hand cursor and does not respond on click

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by humancompanion-usds** [comment] 2023-01-27 16:28
> That being said, there remains to be some argument in the a11y community over whether or not the current page should (or shouldn't) be a link.

Can you explain the rationale for why it should be a link? It's not a link in the USWDS Breadcrumb and I'm inclined to follow suit.

**Comment by joshkimux** [comment] 2023-01-27 19:36
@RLHecht tagging you here for awareness! This question is a bit more complex than it seems and will need some discovery work. Could we create a ticket for this?

**Comment by humancompanion-usds** [comment] 2023-08-15 21:40
@rsmithadhoc - I cannot think of a reason. Ping the others on Slack if you don't get a response here. We have an opportunity to tell the USWDS team about the breadcrumb issue directly in our monthly calls.

**Comment by laflannery** [comment] 2023-08-16 12:49
@rsmithadhoc and @humancompanion-usds I think my only concern with doing this is the possible difference in styling, especially the breadcrumbs. Right now, the current page breadcrumb is not styled as a link and therefore it's a bit confusing when it receives focus and acts like a link - because it's unexpected. If we move forward with this, could we consider the styling of the current page breadcrumb (and page) so that it's a bit more aligned with standard link styling and not as surprising that it is in fact a link?

**Comment by rsmithadhoc** [comment] 2023-08-21 13:58
Thanks @laflannery, I agree, it should look like a link if we go that route. I'll check with the team on that styling change.

In the meantime, I'll work on fixing the issue with the link being clickable.

**Comment by rsmithadhoc** [comment] 2023-08-21 13:59
<img width="1792" alt="Screenshot showing current breadcrumb and the proposed change" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/aae888a2-76a4-4ed1-98f8-d8a31085b9cf">

**Comment by humancompanion-usds** [comment] 2023-08-21 16:19
Hmm. I see the discovery ticket (#53331) that was raised the last time this came up doesn't have much traction. I have some observations:

1. **Potential for information entered to be lost.** For sighted users, having the current page represented as a link was historically thought to be confusing because it may raise the question of whether or not one is at the final level (i.e. am I at this level/page or is there another level/page?) I do wonder if making it a link would cause users to click on it thereby potentially reloading the page. IF we make the breadcrumbs in forms flows simply a back link then I'm not concerned (and we are working towards that with a test of that slated for early next month). We could also make it an anchor link to the h1 of the page. But currently that is not the case and thus clicking the current link would discard any data entered into a form, which is a cardinal sin worse than, for example, the focus state being odd.

2. **Lack of consensus.** There was a suggestion in the thread that Josh captured in #53331 that the current page should just not be included at all. This makes me think there may not be consensus yet and that an A/B test, at minimum, is in order. 

Changing a USWDS component requires some research with users to back it up. Alternatively, you could attempt to convince their a11y folks that this is just a bug and inconsistent with the pagination guidance and thus a change we should make now. As I mentioned, we can bring it up with. At the moment I'm more inclined to let the team that raised this finish their discovery and conduct a test before we create a PR to USWDS. We have opinions but no research with users to conclude that this change is superior to the current design.

**Comment by rsmithadhoc** [comment] 2023-08-21 16:28
Thanks @humancompanion-usds, fair enough, let's wait for discovery from the team that raised this to give us a solid path forward and avoid rework. I'll hold off on changes here.

**Comment by caw310** [comment] 2023-08-21 16:43
Moving to backlog to be worked on in the future.

**Comment by humancompanion-usds** [comment] 2023-10-05 21:59
@caw310 - When we moved this to the backlog we failed to move 2068 and 2117 so now we've already gone and done this. I'm going to go ahead and update the guidance to match what we've done rather than have us undo this. But in future we need to be more careful when our issues are split into many issues and we pause on something that we pause across the board.

**Comment by 1Copenut** [comment] 2024-11-07 20:26
Seeing this issue is still open, could I add a contrarian opinion that we **should** prevent clicks on the last (current) breadcrumb? I know this breaks with the WAI-ARIA pattern but feel we have a couple of compelling reasons to deviate:

1. The [VADS breadcrumb](https://design.va.gov/components/breadcrumbs) has a current behavior where it becomes an anchor link to the `#content` container. This feels like a deviation from expected behavior; breadcrumbs are typically thought of as going to new pages rather than in-page anchors.
2. We do have quite a few "island" React applications inside static containers. Depending on what flow users are in (form flow, for instance) having a breadcrumb that is active and moves to the top of the container could be disruptive.

I did some experimenting with a [simple breadcrumb on a personal repo](https://github.com/1Copenut/vanilla-accessibility-js/tree/main/breadcrumb-list) that used CSS and a small script to effectively cancel the click event and pointer events on the terminal breadcrumb. It still announces as a breadcrumb, still receives keyboard focus, but has a visual and semantic meaning apart from its sibling elements.

I'm happy to discuss this further if there's interest in revisiting.

**Comment by humancompanion-usds** [comment] 2024-11-08 16:22
This issue should not still be open because we've already done all of the work. I appreciate the comment @1Copenut, but I don't have any desire to re-litigate this now. If we end up consuming the USWDS web component and that changes the behavior then I'm sure this debate will come up again and we can discuss the merits of their implementation.

**Closed by humancompanion-usds** 2024-11-08 16:22 UTC
Labels: bug, platform-design-system-team
