### ISSUE TITLE
Cannot submit a form with va-button

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/vets-design-system-documentation#2734] opened 2024-04-16 16:01 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

`submit` on `va-button` does not work. It will not trigger a form submit, so we cannot use this for our form continue buttons.

## What I expected to happen

I expect `submit` on `va-button` should cause the form to submit.

## Reproducing

- Formation version:
- Device: Windows 11
- Browser: Chrome

Steps to reproduce:

Try this HTML
\<form onSubmit={e => console.log("Submitted!")}\>
  \<va-button submit text="Submit va-button" /\>
  \<button type="submit">Submit button\</button\>
\</form\>
Notice va-button does not submit, but the regular button does.

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment] 2024-04-16 18:40
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2734?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment] 2024-04-16 18:45
@caw310 This is a duplicate of this ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2379

**Comment by caw310** [comment] 2024-04-16 19:31
Closing since this is a duplicate. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2379

**Closed by caw310** 2024-04-16 19:31 UTC
Labels: bug, platform-design-system-team
