### ISSUE TITLE
Minor updates to Alert - Expandable component

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/vets-design-system-documentation#904] opened 2022-05-25 15:01 UTC
## What

Based on our experience implementing the new "Alert - Expandable" component for the new Facility COVID status, we have a few suggestions for improvements. 

### Issue #1: At certain combinations of viewport and text length, the carat wraps on a line by itself

<details><summary>Screenshot</summary>

https://www.va.gov/alaska-health-care/locations/

<img width="765" alt="Locations___VA_Alaska_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/170289179-4a0e10ec-6d94-4308-a17a-81e578ff688b.png">

</details>

Proposed solution:  Don't let the carat wrap on a line by itself. Either keep it aligned right, like the Accordion component, or prevent text wrap immediately before the carat.

### Issue #2. Long text wraps under the icon. 

<details><summary>Screenshot</summary>

<img width="296" alt="Locations___VA_Alaska_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/170289470-35d65edd-f6ca-41ae-ac1e-752b424bb0e8.png">

</details>

Proposed solutions: 
a) Limit text length (this will be very difficult from a content govenance perspective)
b) Indent the 2nd line so that it aligns with the first line, like in the non-experimental [Alert component](https://design.va.gov/components/alert)

<details><summary>Alert</summary>

<img width="579" alt="Alert_-_VA_gov_Design_System" src="https://user-images.githubusercontent.com/643678/170290467-de8e9479-2499-4ab3-ab35-958f868ce4a9.png">

</details>

### Issue #3: Defect with the height (UPDATE: this issue is now being tracked in #1093)

In certain situations, the `--calc-max-height:calc(192px + 2rem);` incorrectly calculates the height.

<details><summary>Screenshot</summary>

<img width="928" alt="Locations___VA_Alaska_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/170291173-c8a05d6d-0832-45c5-8e82-d53d30763e3a.png">

</details>

This seems to happen when the `alert-body` is longer, like the "Levels high" variant in [Alaska](https://www.va.gov/alaska-health-care/locations/). It doesn't happen the Low variant (eg [Memphis](https://www.va.gov/memphis-health-care/locations/). It's only happening on the Locations List page, but not on the indivdidual facility pages. 

Solution: CSS or js updates?

### Issue #4: Vertical rhythm / padding issue

Depending on the HTML of the `alert-body`, the top and bottom padding seem excessive. `<p>` or `<ul>` each contain top and bottom margins, which may be creating unintended padding. 

<details><summary>Screenshot</summary>
<img width="596" alt="Locations___VA_Memphis_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/170292334-1bafa2d7-4dc6-44be-8758-c3fad2c1c5c4.png">

</details>

Proposed solution: Unclear. Possibly make padding exceptions for `p:first` and `ul:first`, and  `p:last` and `p:last` in the component, but there's probably a better way? 

### Issue #5: Remove left and right margin

This one we're really not sure about, but submitting anyway. 

In `margin: 0px 1.2rem 0.8rem;` the left/right 1.2rem seems like an assumption? seems like `va-alert` has no left/right margin. 

<details><summary>Screenshot</summary>

<img width="1338" alt="Anchorage_VA_Medical_Center___VA_Alaska_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/170293396-e7fd9236-870c-4689-8ae6-dc222176d68d.png">

</details>

## Why
> Explain why you think this should be added to the VA.gov design system.
>
> - What evidence do you have that it's needed by multiple services across VA?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the VA.gov Design System? 

See above. 

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #platform-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your request is approved, you can [add your component or pattern to the system](https://design.va.gov/about/contributing-to-the-design-system#4-add-your-component-or-pattern-to-the-system). If you have any questions on how to add your component or pattern to the system, please reach out to the Design System Team at #platform-design-system.

**Comment by humancompanion-usds** [comment] 2022-08-02 13:58
@k80bowman - I was able to repo the first issue in here by removing the icon in Storybook. That variation can leave the carat dangling. I agree it could/should work like an Accordion. I wonder if Additional Info has this same bug?

I also agree with issues 2 and 4 in this bug. 4 will require some redesign work.

**Comment by k80bowman** [comment] 2022-08-02 14:03
@humancompanion-usds I was just able to reproduce the first issue in additional info as well, so the answer is yes, it does have the same issue. We'll want to make sure to fix that as well.

**Comment by caw310** [comment] 2022-08-04 16:58
Decision to fix the simpler items and then create ticket(s) for more complex ones.

**Comment by k80bowman** [comment] 2022-08-04 19:28
Some notes:
1. Issue #1 needs to be fixed for both the Alert - Expandable component and the additional-info component. I don't think we want to keep it aligned right (check with @GnatalieH to be sure), so the better solution is to not let it wrap on its own.
2. The solution for issue #2 should be similar to what we have for the background alerts with icons, though the icon size is smaller (1.6rem vs. 2.4rem)
3. I'm going to break #3 out into a separate ticket. We use the same height calculation for this component, va-alert, and va-additional-info, so if it is breaking here it could be breaking in those as well. We might also want to move this calculation into a shared function, so the components can share it and we have a single source of truth for how we calculate component height.
4. I'm going to break #4 out into a separate ticket. The work won't take much to do, but it may take some time and coordination with @GnatalieH to determine how to handle the situation. We have other components where we remove the margins for `p` and `ul` elements inside of a component, but since we don't know how many there will be inside this component, we should be careful.
5. The margin mentioned in #5 has [already been removed](https://github.com/department-of-veterans-affairs/component-library/pull/469). No additional work is necessary.

**Closed** 2022-08-11 21:04 UTC
Labels: vsp-design-system-team, va-alert-expandable
