### ISSUE TITLE
DS Playground: Add `va-button` and `va-button-group`

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1649] opened 2023-03-29 18:54 UTC
## Description
In order to demonstrate compatibility between v1 and v3 components when loaded on the same page, the `va-button` and `va-button-group` components should be added to the DS Playground's "V1 and V3 Side-by-Side Demo" page.

**va-button story**: https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary
**va-button-pair story**: https://design.va.gov/storybook/?path=/docs/uswds-va-button-pair--default

## Additional Info
- The design system playground is on the `ds-playground` branch in vets-website.
- Create a feature from the `ds-playground` branch for this work.
  - **Important**: Merge `main` into `ds-playground` before creating a feature branch
- Create a PR that merges your feature branch into the `ds-playground` branch.

https://github.com/department-of-veterans-affairs/vets-website/tree/ds-playground/src/applications/ds-playground

## Acceptance Criteria
- [ ] The V1-compatible and V3-compatible versions of this component render correctly and function correctly when loaded simultaneously within the DS Playground app.

**Comment by caw310** [comment] 2023-03-30 17:34
Closing as this is a duplicate of this ticket although this issue has more details so they're cross linked. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1627

**Closed by caw310** 2023-03-30 17:34 UTC
Labels: vsp-design-system-team
