### ISSUE TITLE
Header outlines are showing green instead of gold

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/vets-design-system-documentation#1602] opened 2023-03-10 15:43 UTC
# Bug Report

- [X] I?ve searched for any related issues and avoided creating a duplicate issue.

## What happened

From @Mottie - Our form used to show a gold focus outline when focusing on H3s, but now when a header is focused inside a web component I see a green focus outline.

Slack: https://dsva.slack.com/archives/C01DBGX4P45/p1677606674323869

## What I expected to happen

Header outlines should revert to their original golden color.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [X] This bug is not blocking any work
- [ ] Other

**Comment by jamigibbs** [comment] 2023-03-10 18:48
@Mottie Do you mind providing a link to where this screen recording was done?

![h3-focus-outlines](https://user-images.githubusercontent.com/872479/224400357-7fc348d0-bcaa-418e-b741-f705b029585d.gif)

**Comment by Mottie** [comment] 2023-03-10 18:58
The outline is completely gone now 😞 

The page you're seeing is our [Supplemental Claim form](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/) - log in user 228 (Colder)

**Comment by jamigibbs** [comment] 2023-03-10 19:42
@Mottie Did you observe the green border before/after/during working on this PR?  https://github.com/department-of-veterans-affairs/vets-website/pull/23416

I'm also unable to reproduce (or get any focus border whatsoever). We might want to revisit the utility functions that were added as part of that PR to at least get the focus (in any color) working again.

**Comment by Mottie** [comment] 2023-03-10 20:02
I noticed it after that PR was merged, but I guess I only saw it for one day... I forgot about it until I saw the green outline in the video from Peter Russo in the accessibility help channel yesterday.

**Comment by jamigibbs** [comment] 2023-03-10 20:04
FWIW, if I isolate the focus utility functions in Storybook, it appears to be working:

- https://github.com/department-of-veterans-affairs/component-library/pull/646

<img width="497" alt="Screenshot 2023-03-10 at 2 01 46 PM" src="https://user-images.githubusercontent.com/872479/224416988-19d84f01-a1b9-4c55-9090-aaa70c2c1442.png">

**Closed** 2023-04-19 19:49 UTC
Labels: bug, vsp-design-system-team, CoP FE Help
