### ISSUE TITLE
Screen Reader bug: Signature / Statement of Truth (JAWS)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/vets-design-system-documentation#2649] opened 2024-04-02 18:47 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

This bug was discovered during a [research study focused on Accessibility](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/accessibility_research/research-findings.md) for the [Financial Status Report](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction). 

Angela Fowler, using JAWS, suggested that the the full name error message needs to be put in an aria-live region and be made polite so that it reads the error message.

There was also one participant who was also using JAWS who stated it wasn’t completely clear that he was signing a form, he also could not access the error field that states the name.

<img width="598" alt="Screenshot 2024-04-02 at 1 36 57 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/5553542/009f364b-d1a0-4051-8604-8b06e22b80f2">

## What I expected to happen

- It should be clear to users utilizing screen readers that they are signing a form. 
- All screen readers, including JAWS, should read the error message on the signature form (including the user's name)
- Any accessibility improvements should be incorporated into the [Signature](https://design.va.gov/patterns/ask-users-for/signature) and [Statement of Truth](https://design.va.gov/components/form/statement-of-truth) Design System components

## Reproducing
Windows
JAWS

Steps to reproduce:

1. Navigate to the Confirmation page of the [Financial Status Report](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction) (user81)
2. Utilizing JAWS, navigate to the signature/statement of truth section of the [Confirmation page](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit)

## Urgency
How urgent is this request? Please select the appropriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [x] Other - This was a planned ticket in our current Sprint [#66853](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66853)

### Details

There are two open issues that are related to VoiceOver but not JAWS
- [va-text-input and va-textarea error message not announced by screen readers #2572
](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2572)
- [Discovery: Research and propose aria-describedby alternatives #2619](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2619)

**Comment by mgleo** [comment] 2024-05-15 16:42
Hi @rsmithadhoc, thank you for looking into this.
The comments on this ticket [#66853](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66853) give some more context into the issues. This [slack thread](https://dsva.slack.com/archives/C8E985R32/p1712080170889669?thread_ts=1712003691.475189&cid=C8E985R32) also contains more information. There were other issues that were similar that were referenced here, so the issue may have been resolved: 

- [#2572](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2572)
- [#2619](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2619)

There is also an additional usability issue where a screen reader user did not know they were signing a form.

**Comment by rsmithadhoc** [comment] 2024-05-17 13:58
Hi @mgleo ,

Thanks for the additional info. For these:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/66853 was an issue with specific Mac and VoiceOver versions, but it is resolved in future updates. I also tested in JAWS and it read out everything as expected, so I'm not sure what the issue may have been there.
- For screen reader user not knowing they were signing a form, I also confirmed that the field information does get read out as expected.
  - Even though it read out on my end, I could still see that it can be unclear that you are signing a form. I think the verbiage could be updated to better reflect that. It says signature above, but not in the actual field description or labels itself (see screenshot), so the user would not hear the word "signature" if they tabbed to this field. These fields are customizable in the component.
  <img width="823" alt="image" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/d55fbb4d-dfc0-42ba-a55c-f21094a9611c">


Because I was able to confirm that all the field information and error messages were read out as expected, I'll close this issue out. But let us know if you run into any other issues.

Thanks!

**Closed by rsmithadhoc** 2024-05-17 13:58 UTC
Labels: bug, accessibility, platform-design-system-team
