### ISSUE TITLE
Loading indicator error on route

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/vets-design-system-documentation#1349] opened 2022-11-23 00:13 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
Part of the errors described in this thread: https://dsva.slack.com/archives/C01DBGX4P45/p1669047962953369

In React, when showing a va-loading-indicator, then routing to a new page the loading indicator seems to have an error with its disconnect.
![Screen Recording 2022-11-22 at 4 07 51 PM](https://user-images.githubusercontent.com/13967174/203445909-01e872b2-63b4-4cd0-86e0-b5a4f37d6076.gif)

## What I expected to happen
Expected the loading indicator to not produce an error to the console.

## Reproducing
- Formation version: ?
- Device: (Macbook)
- Browser: (chrome)

Steps to reproduce:

1. Create a loading page with the va-loading-indicator rendered
2. In a useEffect route to a new page 
3. Observe the error

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work (very minor issue, lowest priority)
- [ ] Other

**Comment by jhonnyoddball** [comment] 2023-01-03 20:23
@brianseek Do you still have this problem? If so, do you have a branch where I can reproduce this error?

**Comment by brianseek** [comment] 2023-01-04 19:43
@jhonnyoddball this is still happening, you can see it on the main branch of vets-website. It happens on stage or locally. Let me know if you want to co-work on getting the app running locally to see it or if you want to see how to set a test appointment up on stage to view it there.

**Comment by jhonnyoddball** [comment] 2023-01-09 20:44
After several attempts (20+) to replicate this error, I was not able to replicate it. I believe it's a race condition of some kind. After meeting with Brian, he mentioned that it was not occurring as often as before.

I'll be closing this ticket since I was not able to replicate it. If you encounter this error again, please feel free to reopen this ticket.

**Closed by jhonnyoddball** 2023-01-09 20:44 UTC
Labels: bug, vsp-design-system-team, Stretch
