### ISSUE TITLE
Ask a user for their... Housing status/situation

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/vets-design-system-documentation#2784] opened 2024-04-26 18:56 UTC
### Duplicate check

- [ ] I've searched for any related issues and avoided creating a duplicate issue.
**NOTE: I missed the related issue and this is now a duplicate ticket.**
  - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1371

### This update is for:

Pattern

### What is the name?

Ask a user for their... Housing status/situation

### What is the nature of this update?

- [ ] How to build this component/pattern
- [X] When to use this component/pattern
- [ ] When to use something else
- [X] Usability guidance
- [ ] Accessibility considerations
- [X] Content considerations
- [ ] Implementation
- [ ] Package information
- [ ] Addition to Forms Library documentation
- [ ] Update to existing Forms Library documentation

### What problem does this solve?

Provides a plain language way to ask Veterans their housing status that allows them to answer the question accurately and without shame

### Additional Context

We worked with @DanielleThierryUSDSVA  on this content

[I pulled out the specific pieces into this figma file](https://www.figma.com/file/PgZ1U35raBde6s3viqotpA/WIP-DSC---Pattern---Ask-Users-for-Housing-Situation?type=design&node-id=1-8&mode=design&t=nuRmgBaAuoNH1Vmz-11). 

You can see it in action in this form - [Request priority processing for an existing claim 20-10207](https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207)

[You can also see it in use in the forms figma file here](https://www.figma.com/file/DA6OjFz20kUa9ecElv9zPE/WIP---20-10207-Priority-Processing?type=design&node-id=0-1&mode=design&t=hzwRSIpijLvb77Ia-11)

<img width="566" alt="0-Homeless-Q-1" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/c18e4269-96aa-4cf8-92f3-397571b2ca5b">
<img width="509" alt="1-Homeless-None" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/a581ea8a-f646-4a26-9551-f05e52496e8b">
<img width="545" alt="1 1-mailing-address" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/c294634c-4be6-449d-a872-5e07b48a54d9">
<img width="507" alt="2-Homeless-Q-triggers-optional-address" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/cc646592-352f-42cb-9de7-d770d5ef2132">
<img width="542" alt="2 A-other-housing-risk" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/a7fa85e5-b7dc-4b14-87c0-600169fda09e">
<img width="526" alt="2 B-Address-Optional" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/efa5da89-42b1-481c-ba17-3dd849a6855d">
<img width="540" alt="2 B-No-PhoneEmail" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/fca60b64-73b0-47d5-a698-b5a79666784f">
<img width="545" alt="2 B-Yes-mailing-address" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/8d2281d4-16be-4dbe-b45a-621c1ea01683">
<img width="541" alt="2 C-homeless-point-of-contact" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/0e31bd6f-4b85-4ef7-b74d-ded73fccbf5e">
<img width="496" alt="3-Homeless-Q-Other" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/eca6bf3f-df9e-41e0-a07a-ff0bcc7f4495">
<img width="542" alt="3 A-other-housing-risk" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/c6344ccc-6b78-43cd-b51a-b2f1878d0218">
<img width="526" alt="3 B-Address-Optional" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/63effe77-4c39-4278-9890-99679c93283a">
<img width="540" alt="3 B-No-PhoneEmail" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/966b4255-73eb-4d0a-9a06-c191bbbedbdf">
<img width="545" alt="3 B-Yes-mailing-address " src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/2dc8d66e-70f5-479f-8371-1182aabd9977">
<img width="541" alt="3 C-homeless-point-of-contact" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/117098918/79c587c2-70a0-4368-ad64-f21eee3b1ed0">

**Comment by caw310** [comment] 2024-05-29 14:47
Closing as this is a duplicate of  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1371

**Comment by humancompanion-usds** [comment] 2024-07-17 19:24
Reopening this to track my work as it is in our repo and thus easier to link to.

**Comment by humancompanion-usds** [comment] 2024-07-25 13:41
Deployed! https://design.va.gov/patterns/ask-users-for/housing-status

**Closed by humancompanion-usds** 2024-07-25 13:41 UTC
Labels: documentation-design.va.gov, platform-design-system-team
