### ISSUE TITLE
Request for notification design component

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/vets-design-system-documentation#606] opened 2021-12-21 19:31 UTC
Check the [design system backlog](https://design.va.gov/documentation/backlog) and [experimental design tab](https://design.va.gov/experimental-design/) to see if your proposal has already been suggested. 

## What
> I am proposing a [new component ](https://preview.uxpin.com/977f0f0595c247c52d7661de178e364ea0a882bb#/pages/145604742/simulate/no-panels?mode=i)for personal on-site notifications. 

We are working on an on-site notifications feature, which will notify users to any action needed or important changes to their personal benefits. Currently we only have 'Alert' components, which address general VA concerns/errors. It would be confusing to users to see an alert used as a personal notification since those are fundamentally different use cases. We currently do not have a component to notify users of changes to their personal benefits or alert them to action needed, so we are proposing a new component specific to personal notifications.

## Why
> Explain why you think this should be added to the VA.gov design system.

We are working with VA Notify on an on-site notifications feature, which will notify users to any action needed or important changes to their personal benefits. Currently in the VA design system we only have 'Alert' components, which address general VA concerns/errors. It would likely be confusing to users to see a personal notification styled as an 'Alert' since they are fundamentally different use cases. We currently do not have a component to notify users of action needed or changes to their personal benefits, so we are proposing a new component specific to personal notifications for logged-in users.

For our MVP, we plan to focus on one singular notification (debt notification) to start building the infrastructure to manage more robust on-site notification needs in the future.

You can read more in [the notifications product outline.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/mvp)

Also in [the comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/action-items-comparative%20analysis.md) around notifications, it became clear that it is common practice to have a specific design dedicated to personal notifications -one that is different from a site-wide alert or page error.

> What evidence do you have that it's needed by multiple services across VA?

The purpose of the My VA dashboard + the overall Authenticated Experience is to bring together services that a user has in one centralized place. Many of the design components that currently exist are meant for general content pages, not personalized information. By creating a notification component it naturally will be utilized by many services across the VA in the logged-in state. Furthermore, [when our team did research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/research/alerts-discovery-research-summary.md) earlier this year using the card component, users clearly stated that they want any time-sensitive action items or issues to be clearly prioritized.  This new notification component will prioritize that information.

The onsite notifications work will touch many different services on VA.gov including (but not limited to) education benefits, compensation benefits, pension benefits, debt payments, secure messaging, prescriptions and health care appointments.  There should be a unified design that clearly lets users know that there is important time-sensitive personal information regarding their benefits.   

> What evidence do you have that it meets the needs of the users of those services?

We will be running usability testing in early January with this new component to ensure that it elevates time-sensitive information. We will be running this research with the following goal in mind:

- Understand if the notification interaction design meets user expectations and needs, or determine where it does not meet user needs and expectations.

We have the following questions outlined in [our research plan.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-research-plan.md)

- Does the proposed MVP solution (a single dismissible debt notification displayed at the top of the page) help Veterans to more easily take action on their payments or debts?
- Why would a user want to dismiss this alert?
- What do users expect to happen after an alert has been dismissed?
- Are there any areas where the design does not meet Veteran needs?
- When does a user expect to see an alert about new debt?
- If a user has a new notification on VA.gov, how would they know?

> Have you checked that it doesn't already exist in the VA.gov Design System? 

Yes

## Anything else
- [Notifications product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/mvp)
- [Specs for new notifications link style](https://preview.uxpin.com/977f0f0595c247c52d7661de178e364ea0a882bb#/pages/145604742/simulate/no-panels?mode=i)
- [Potential levels of notifications](https://app.uxpin.com/edit/8984028/#?id_page=145867219)
- [Example of new notifications link style](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=tressafurner7646) (Note - the notification may or may not be dismiss-able depending on the use case)
- [Action items research synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/research/alerts-discovery-research-summary.md)
- [Notifications + Payment information research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-research-plan.md)

## Next steps
You may present your work to the Design System Council at an upcoming meeting. If you do not or cannot attend the Design Council Meeting, you can opt to get an asynchronous approval. 

Submit requests to join an upcoming Design System Council meeting in #vsp-design-system.  

During the meeting, the Design System Council Working Group will evaluate the request and make a decision. 

If your component request is approved, you can add your component to the [experimental section](https://design.va.gov/experimental-design/) on design.va.gov. If you havee any questions on how to add your component to the experimental section, please reach out to the Design System Team at #vsp-design-system

**Comment by caw310** [comment] 2021-12-22 15:07
@tressaellen , this will be discussed at the Jan 7th Design System Council meeting.

**Comment by Samara-Strauss** [comment] 2021-12-22 16:44
@caw310 would it be helpful for us to have already conducted user testing before this is brought to the design council? If so, we might want to push back which meeting this is discussed in. cc/ @tressaellen

**Comment by caw310** [comment] 2021-12-22 17:41
@Samara-Strauss , it isn't a requirement that user testing be done before this is brought to the design council. It would help for you to mention that you'll be doing user testing and to talk about how you will measure success.

**Comment by tressaellen** [comment] 2021-12-22 17:48
I can add that in!

**Comment by Samara-Strauss** [comment] 2021-12-22 18:13
Noted -- thanks @caw310!

**Comment by bkjohnson** [comment] 2022-01-03 21:13
Have desktop push notifications been considered for this? You can see a simple demo here: https://pushalert.co/demo

**Comment by Samara-Strauss** [comment] 2022-01-03 22:13
@bkjohnson push alerts have been considered for the mobile app, but not yet for the in-browser experience since we're just getting that off the ground.

**Comment by caw310** [comment] 2022-01-07 18:52
@tressaellen , following up from the DSC meeting. Thank you for presenting. As mentioned, there is no decision needed. 
The DSC would like to hear what you learned from testing specifically around these areas: 

- Trauma
- Perceivability in where they site in sequence of page
- Comprehension if moved on page

**Comment by Samara-Strauss** [comment] 2022-01-10 16:10
Pulling in @andaleliz to this ticket since @tressaellen is rolling off the team at the end of this week 😭 @caw310 -- you'll want to follow up with Liz as needed.

**Comment by andaleliz** [comment] 2022-03-11 21:09
Hello! I'm revisiting this ticket in hopes we may be able to close it out. Ultimately, we're not moving forward with the component as designed, because **low vision users had trouble reading the link color against our background-only warning alert color**.  

I still think it's worth sharing the feedback we got in testing related to the points you brought up. The component still has merit, especially if we reconsider the background color for a warning state, or perhaps bold the links. [Here's the prototype version of what tested](https://preview.uxpin.com/45251888896c8dd47ef62aa20d3a89a334726ac1#/pages/145483168/simulate/no-panels?mode=i).

>Trauma

No participants in our study showed any signs of distress or being triggered.  On the contrary, multiple participants commented that they found the yellow color "soothing" and said it didn't communicate an appropriate level of urgency if they owed money to VA (our context was debt notifications)

I'm not sure I'm interpreting rest of these correctly, so please let me know if this isn't the information the DSC was interested in:

> Perceivability in where they site in sequence of page

My interpretation of this bullet is is "do people perceive this on the page when it's mixed in with other content?".  Yes, people easily noticed the notifications throughout the page on My VA. 

> Comprehension if moved on page

My interpretation of this bullet is is "do people understand what happened if they dismiss the alert and it goes away?". Yes, people understood what happened and weren't confused by the disappearance of the alert after the closed it.  Otherwise the alerts don't move around on the page so I'm not sure what else this could mean.

I'm not sure what this means for consideration of adding a notification component to the design system but thought it would be worth sharing this information.

**Comment by Samara-Strauss** [comment] 2022-03-11 21:15
I think we can close out this ticket since we changed the design to use an existing component. This was opened to gain approval for the light yellow background design, but since we aren't using that, this ticket is no longer needed. Thanks for following up, Liz.

**Closed by Samara-Strauss** 2022-03-11 21:15 UTC
Labels: vsp-design-system-team, experimental_design

**Comment by GnatalieH** [comment] 2022-03-14 19:53
@andaleliz thank you for sharing that feedback. Really interesting results! I'll be sure and leverage these test results if/when we move forward with a notification component.
