### ISSUE TITLE
CSS Library: Generate a Figma token file

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1957] opened 2023-07-31 20:14 UTC
## Description

Reference discovery ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1837

An NPM package exists that we could use for Figma: [style-dictionary-to-figma](https://www.npmjs.com/package/@divriots/style-dictionary-to-figma). I connected this package and [generated a tokens file](https://github.com/department-of-veterans-affairs/component-library/blob/37b576f1ba88d9839daac99fbd1ce507be8232dd/packages/css-library/dist/figma/tokens.json) with it as part of this discovery work but this will need to be verified that it's working as expected as part of the development ticket.

The [Figma documentation](https://www.figma.com/community/plugin/1128196356923537195/Sync-Design-Tokens) says that you can import/use that file just by linking to its [public source](https://raw.githubusercontent.com/department-of-veterans-affairs/component-library/37b576f1ba88d9839daac99fbd1ce507be8232dd/packages/css-library/dist/figma/tokens.json).

This design token validator might be useful too https://animaapp.github.io/design-token-validator-site/

## Tasks
- [ ] A token files has been created in the CSS Library that works with Figma

## Acceptance Criteria
- [ ] The token file has been tested for Figma and confirmed to work as expected.

**Comment by ataker** [comment] 2023-08-17 18:41
Here are the steps to add the color token to Figma:

1. In Figma, open the top left Figma menu, then select Plugins, then Sync Design Tokens 
![Sync Design Tokens Menu](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1413938/73a4a5c8-e464-43aa-ad94-00b991c4b062)

2. In the modal form, for the Tokens json file url enter the [URL for our token file](https://raw.githubusercontent.com/department-of-veterans-affairs/component-library/figma-colors-token/packages/css-library/dist/tokens/figma/variables.json) and for case type select the Camel radio button. Click the Import Tokens button.
3. The colors should populate under Local Styles in the right side menu.

@LillyBoot 

Note to self: our token URL will need to be updated after the pull request is merged in.

**Comment by LillyBoot** [comment] 2023-08-17 19:17
@ataker the design tokens were able to import with no issue! The only minor thing I noticed was that some of the color names came in as an asterisk. Not sure if that is something you could fix on your end. If not we can always change it manually in Figma
![Screen Shot 2023-08-17 at 3 14 04 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123974487/11c2d5da-2ced-463c-9e66-5e51ab746fdc)

**Comment by ataker** [comment] 2023-08-17 20:18
@LillyBoot Updated so they have the name, and all the alternates are prefixed with the group they're in:

![Screenshot 2023-08-17 at 4 12 42 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1413938/ea41aaf5-cfc2-4218-9978-5a222169cb57)

The base ones now end with a hyphen though, I don't think I can help that.

**Comment by LillyBoot** [comment] 2023-08-17 20:24
@ataker thank you for fixing that! It looks much better.  
![Screen Shot 2023-08-17 at 4 22 06 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/123974487/e03b71fd-f698-4ac3-a73f-637971c0b55f)

@humancompanion-usds any thoughts?

**Comment by humancompanion-usds** [comment] 2023-08-22 16:21
Looks good. I'm still working through the colors in tokens. There are some I'd like to rename/move:

* warning-message should become feedback-warning-background. It's MVP value is #fac922 but it will move to match the USWDS value of uswds-system-color-yellow-5 (#faf3d1) in the final v3 color set. 
* gibill-accent. I'm not sure this is still in use or if it's a hub color or what. Can we investigate? That will help me rename it.
* orange. What in the world is this doing there?! It's such an odd call out. That too needs some investigation. Is it in use? Is it a hub color? What is it? That will help me rename it.

Otherwise the list looks complete to me in Figma.

**Comment by ataker** [comment] 2023-08-25 21:27
[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25405) should address all three colors:

- `warning-message` updated to `feedback-warning-background`
- `gibill-accent` has been removed. This was a duplicate of `gold-lightest` only used in the GI Bill portion of `vets-website` (which I have a separate PR to update that to the more standard name)
- `orange` has been removed. This was only used within storybook. Moved to a more appropriate location

**Comment by ataker** [comment] 2023-08-29 20:27
We still need to remove `warning-message`, which will be handled in [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2047)

**Closed by ataker** 2023-08-29 20:27 UTC
Labels: platform-design-system-team, dst-engineering
