### ISSUE TITLE
va-icon: Fix the sprite.svg path for the Storybook production site

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/vets-design-system-documentation#1977] opened 2023-08-04 17:37 UTC
## Description

The va-icon Storybook page is not loading the `sprite.svg` file but it does work in Chromatic links and locally:

- https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default

![Screenshot 2023-08-04 at 12 36 26 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/9a1e22f8-c25b-4350-bb0e-37cbff157dbf)

![Screenshot 2023-08-04 at 12 37 01 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/f5511460-46ff-47a4-8721-1550aabc3c13)

The production site adds `/storybook/` to the url which we believe is what might be causing this. So we probably have to make sure the sprite file loads for both `[url]/storybook/assets/sprite.svg`  and `[url]/assets/sprite.svg` paths.

A possible solution is to add another folder to the Storybook `assets` folder so that it maps to both of these locations. The downside to this is that we would have to manage the sprite sheet in two locations for Storybook.

![Screenshot 2023-08-01 at 4 07 38 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/872479/be48d13c-67cc-429c-979c-9bd1286516a2)

## Tasks
- [ ] Make sure the sprite.svg file is loading locally, in Chromatic, on Storybook prod, and also that va-icon still works in vets-website

## Acceptance Criteria
- [ ] va-icon works locally, for Chromatic, in Storybook prod, and vets-website.

**Comment by caw310** [comment] 2023-10-05 16:38
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1977?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by caw310** [comment] 2023-10-05 16:44
This should be worked on before 66068 https://github.com/department-of-veterans-affairs/va.gov-team/issues/66068 as it should fix the icon issue.

**Comment by powellkerry** [comment] 2023-10-12 14:51
@harshil1793 I started looking into this yesterday because it is mentioned in my card. From what I can tell in the AWS S3 bucket, the sprite.svg exists in the same storybook/assets directory in prod as it does locally. I am not sure why prod would be trying to load that from a different directory.
I tried to copy the sprite.svg file to the root assets directory in prod so that I could test @jamigibbs theory, but I didn't have the permissions to do it in AWS.

**Comment by powellkerry** [comment] 2023-10-12 20:48
I have verified, through using the "Requestly" chrome application that it is trying to load the icon from the root, and not from the storybook directory.

**Comment by caw310** [comment] 2023-10-23 19:08
This is more complex than initially thought so will carry over into the next sprint.

**Comment by harshil1793** [comment] 2023-10-23 19:09
On localhost, `sprite.svg` is correctly resolved. However, in production, it's incorrectly pointing to the same path as on localhost, resulting in a 404 error.
In the production environment, when accessing https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default, the path for sprite.svg is https://design.va.gov/assets/sprite.svg, which results in a 404 error. However, manually accessing https://design.va.gov/storybook/assets/sprite.svg gives a 304 status, which suggests that this should be the correct path.
To address this, I was thinking to declaring conditional paths based on the environment.
However, when testing this change in Chromatic, I encountered a 500 error, and I'm uncertain about the cause. I was under the impression that the Chromatic and production builds were identical.

**Comment by micahchiang** [comment] 2023-10-30 16:15
Reopening until we get some clarity from @harshil1793 on what else needs to be done.

**Comment by jamigibbs** [comment] 2023-10-30 16:22
> I have verified, through using the "Requestly" chrome application that it is trying to load the icon from the root, and not from the storybook directory.

Is the root `design.va.gov`? If so, have we tried adding the sprite sheet to the [documentation repo](https://github.com/department-of-veterans-affairs/vets-design-system-documentation) to see what happens? That might not be a long term solution but it might help us understand more about the behavior if it works.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--767a87c4f5241f0b2d3bda7a524ed409b5614111/Screenshot%202023-10-30%20at%2011.20.42%20AM.png)

**Comment by jamigibbs** [comment] 2023-10-30 16:57
@harshil1793  To add to the comment above, if it works to have the sprite file in a directory in that repo, maybe we can write a gulp task to grab it from the component-library package and move it wherever we need it? Like how it was done here for the formation images?

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/config/gulp/images.js#L4-L11

**Comment by harshil1793** [comment] 2023-10-31 16:59
I believe implementing a gulp task is an effective approach. We can organize it such that anything within `/storybook/assets` gets relocated or duplicated to the `/assets` directory at the root. Rather than exclusively designating the path for `sprite.svg`, we can craft a more forward-thinking solution that transfers all assets, thereby resolving the issue comprehensively.

**Closed** 2023-11-02 15:06 UTC
Labels: platform-design-system-team, dst-engineering, va-icon
