### ISSUE TITLE
Typography bug in wizard

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/vets-design-system-documentation#300] opened 2020-09-08 17:06 UTC
# Bug Report
## What happened

In a recent usability study, I noticed the font size changed on every other question in the wizard on va.gov/education/eligibility. The font size for the 2nd and 4th question was noticably larger than on the 1st and 3rd

## What I expected to happen
The font size should be the same on all questions

## Reproducing
- Formation version: I saw this on va.gov, on production
- Device: user had a Samsung galaxy S9
- Browser: I believe they were using Chrome, but could've been the Google app.  Screenshot of app UI is included.

### Steps to reproduce:

I don't have this device, so I can't reproduce. I had a team member try to reproduce but she couldn't. We're not sure what version of Chrome the user had installed or what app they were using (this was not the focus of our study), but still wanted to report in case someone else can reproduce it.

#### screenshot from session recording:
<img width="494" alt="Screen Shot 2020-09-08 at 9 58 48 AM" src="https://user-images.githubusercontent.com/55992116/92506753-eb855a00-f1d3-11ea-909e-6b9c7e04a5f2.png">

#### screenshot of users browser UI (I think this is Chrome?)
<img width="498" alt="Screen Shot 2020-09-08 at 11 01 34 AM" src="https://user-images.githubusercontent.com/55992116/92506752-eaecc380-f1d3-11ea-9f99-64ac7d8d0e15.png">

**Comment by humancompanion-usds** [comment] 2022-06-15 22:08
I just tested this again on Chrome on iOS and was not able to reproduce. Closing.

**Closed by humancompanion-usds** 2022-06-15 22:08 UTC
Labels: bug, vsp-design-system-team
