### ISSUE TITLE
On this page jump links should not have a max width

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#1107] opened 2022-08-15 15:07 UTC
## What happened
On this page jump links have a max width set to 285px. This causes  link text with a lot of characters to wrap in an unnatural way for English and translated content.

Example 1:
![Screen Shot 2022-08-15 at 9.55.19 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/cf9694a5-039a-4b32-a254-e3ac5a9c911d)

Example 2:
![Screen Shot 2022-08-15 at 9.54.24 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/038bb2c3-c723-4fa9-a2f3-4623a5eba20c)

## What I expect to happen
I expect the On this page jump links text to extend to the full width of the main content area, if necessary. We should check with Content to get max character count suggestion for On this page jump links, however.

Example:
![Screen Shot 2022-08-15 at 10.05.04 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/8f32e986-d435-4051-b3a0-b662dd39bb53)

## Acceptance criteria
- [ ] Remove the max width property for On this page jump links.
- [ ] Get guidance from Content on the maximum suggested character count for On this page jump links and update documentation accordingly.

**Comment by humancompanion-usds** [comment] 2022-08-24 13:50
Let's discuss this. USWDS had (can't find it right now) a recommended max-width for paragraphs that used the `ch` CSS unit for measuring width. I want to say it was 66 or 77ch wide. Letting all text go to 100% of the container is not going to result in a more readable line length. Perhaps our current line length is a little draconian but, 100% is not the answer.

**Comment by GnatalieH** [comment] 2022-08-24 15:03
@humancompanion-usds happy to discuss this. My reasoning was that the body text extends the width of the main content area, so I thought these jump links would be OK doing that especially since they are a larger typeface. I read a bunch of articles on usability and line length, and 45-75 characters is considered a best practice. However, there was a newer study that indicated that for on-screen text up to 95 characters is OK.

**Comment by humancompanion-usds** [comment] 2022-09-14 14:50
This is a duplicate of issue #951.

**Closed by humancompanion-usds** 2022-09-14 14:50 UTC
Labels: component-update, vsp-design-system-team, va-on-this-page
