### ISSUE TITLE
Audit Sketch VA Pattern library

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#674] opened 2022-03-25 14:32 UTC
### Steps to complete

1. Compare assets between Sketch library symbols and developed components. 
2. Note in spreadsheet or Mural board where discrepancies occur.

Relates to [#470](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/470).

**Comment by andaleliz** [comment] 2022-03-31 17:16
FYI I think this is a duplicate of #470

**Comment by caw310** [comment] 2022-04-04 18:08
Here is a link to the Google sheet with all audit info.  https://docs.google.com/spreadsheets/d/17Fw7flaFcd4CG24E_bBTb4Hq0AEfrT2ivjHqrjuACos/edit?usp=sharing

**Comment by GnatalieH** [comment] 2022-04-12 15:46
I'd like to close this issue since the audit of Sketch library components compared with developed components work is completed.

**Closed** 2022-04-12 17:54 UTC
Labels: documentation-sketch, vsp-design-system-team, DSC request
