### ISSUE TITLE
Nested list styles are unclear.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/vets-design-system-documentation#142] opened 2019-09-09 18:46 UTC
# Bug Report

The CMS team found `list-style: disc` for unordered lists in an accordion, the Patient advocates accordion on https://www.va.gov/pittsburgh-health-care/health-services/

It seemed like a css bug, but inspecting the css shows ```.usa-accordion-bordered>ul li ul, .usa-accordion>ul li ul {
    list-style: disc;
}```

_accordions.scss shows

```@mixin accordion-nested-list {
  > ul li ul {
    list-style: disc;
    > li > ul {
      list-style: circle;
      > li > ul {
        list-style: square;
      }
    }
  }
}
```

it's unclear, in the design system, if this is desired. Either the design system should be updated to include these variations, either in https://design.va.gov/design/typography or https://design.va.gov/components/accordions.  Or maybe ordered and unordered lists deserve their own page in the system, which can cross-reference the Process list component

![VA_Pittsburgh_Health_Care___Patient_and_health_services___Veterans_Affairs](https://user-images.githubusercontent.com/643678/64558035-f67f8300-d310-11e9-85a1-6d31958d5af2.jpg)

**Comment by KevinMHoffmanUSDS** [comment] 2019-09-11 14:15
@kevwalsh Thanks! Will update once we address. In the meantime, added an example of nested list styles to the typography page, which should go into production this afternoon.

**Comment by kevwalsh** [comment] 2019-09-11 14:50
@KevinMHoffmanUSDS One my team members resolved this by adding to the _shame.scss file https://github.com/department-of-veterans-affairs/vets-website/blob/b594313a5ab5b1abc646b800e616e147b801903a/src/platform/site-wide/sass/shame.scss#L559 

I don't know much about _shame.scss but i'm guessing this is not the right long-term resolution :)

**Comment by KevinMHoffmanUSDS** [comment] 2019-09-11 15:05
@kevwalsh Thanks for the heads up! I have a hunch that you are correct, _shame.scss is not an industry standard. :)

**Comment by KevinMHoffmanUSDS** [comment] 2019-09-13 15:34
@jaredcunha-usds Thanks for the update and recommendations! It's been awhile since I've dealt with production CSS, so clearly the _shame(.css) is mine. 

Really appreciate the analysis! I think we can close this, but I'd like to open a new issue that alludes this this as an example of an area where we can make improvements in the design operations process around 

1. Identifying an inconsistency (if not a bug) in our execution of USWDS/VADS
2. Documenting that inconsistency, and making a governance call on what would be better.
3. Documenting the improvement in the design system.
4. Coding the improvement across production. 

/cc @chrisj-usds (as per our governance discussion this morning) 

I'm going to open a new issue regarding general inconsistencies this issue as a future one to address, and close this issue. This will be a WIP issue.

**Closed by KevinMHoffmanUSDS** 2019-09-13 15:34 UTC
Labels: bug
