### ISSUE TITLE
Formation Deprecation - Swap shared variable imports from Formation to CSS-Library

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/vets-design-system-documentation#2975] opened 2024-06-27 17:15 UTC
## Description
The majority of applications individually [import formation shared variables](https://github.com/department-of-veterans-affairs/vets-website/blob/279780255cdf40e27d39c33197fabd32f307c015/src/applications/disability-benefits/all-claims/sass/disability-benefits.scss#L3). These should be switched to css library using the import path:  
`@import '~@department-of-veterans-affairs/css-library/dist/tokens/css/variables.scss';`

## Considerations
- We'll need to make sure all shared variables imported in [formation/shared-variables.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/9fd9ed35036b0cee4f6d428c28c5c414ebf2092f/packages/formation/sass/shared-variables.scss#L12) are accounted for in [css-library/variables.scss](https://github.com/department-of-veterans-affairs/component-library/blob/fdc8c23fc8ce98c96ddbeea84b72ac0be41a4d87/packages/css-library/src/stylesheets/formation-overrides/_variables.scss#L6)

## Tasks
- [ ] Update the import for all applications that individually import shared variables from formation

## Acceptance Criteria
- [ ] The above tasks have been completed

**Comment by caw310** [comment] 2024-10-16 17:36
Duplicate of #3328

**Closed by caw310** 2024-10-16 17:36 UTC
Labels: platform-design-system-team
