### ISSUE TITLE
[Background only alert] - Update Storybook with real-world examples; replace Buttons with Action links for CTAs

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/vets-design-system-documentation#907] opened 2022-05-26 20:31 UTC
## Description
[Several Background only alert examples in Storybook](https://design.va.gov/storybook/?path=/docs/components-va-alert--background-only) are using a sign-in button for the CTA, and do not reflect real-world use cases. 

## Tasks
- [ ] Update content in Background alerts to match real world use cases
- [ ] Replace button CTA with an Action link wherever necessary

**Comment by k80bowman** [comment] 2022-06-28 14:29
closing as duplicate of #908

**Closed by k80bowman** 2022-06-28 14:29 UTC
Labels: component-update, vsp-design-system-team, va-alert
