### ISSUE TITLE
[Design] Update Button in Figma with new text wrap variation

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/vets-design-system-documentation#3232] opened 2024-08-26 21:14 UTC
## Description
We have a new button variation to account for buttons where the button text wraps to two lines. We need to add that variation to current button. 

## Details
- [Button comment thread in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk?node-id=199-1198#915017480)

## Tasks
- [ ] Update the button in figma for the 1.15 option
- [ ] Rename the button 1.15 to something that Designers will understand to use when button text wraps to two lines. 
- [ ] Review with Designers

## Acceptance Criteria
- [ ] The button has a variation that will change the current button to the two line variation

**Comment by caw310** [comment] 2024-08-27 16:38
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/3232?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by LWWright7** [comment] 2024-08-27 17:25
@caw310 This is a duplicate of [#3089](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3089) the design team was talking about this in our morning sync today.  Is there any way to merge this ticket with 3089 or close one / or the other and just have 1???

**Comment by caw310** [comment] 2024-08-27 19:19
@LWWright7 @babsdenney Please close one of the tickets. I'd say use the one that has better details.

**Comment by LWWright7** [comment] 2024-08-27 19:28
@babsdenney Closing this ticket....I added the info you created on this ticket to #3089

**Closed as completed** 2024-08-27 19:28 UTC
Labels: component-update, platform-design-system-team, va-button, design, DST-Design
