### ISSUE TITLE
Fomration Overrides CSS file for UWDS VA Radio Option input height renders other fields unclickble

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/vets-design-system-documentation#2522] opened 2024-02-21 23:01 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

After upgrading the USWDS versions of the web components, the FSR form has some buttons that are not clickable now because of the way the [Formation overrides CSS file](https://github.com/department-of-veterans-affairs/component-library/blob/e19611c6c21cbb7fc98060817e964e6e4d21a04b/packages/web-components/src/global/_formation_overrides.scss#L51) affecting the `input` field on the `va-radio-option` component. 

The default `uwds .usa_radio-input` styles are being overwritten by the formation override styles causing the issue:

<img width="263" alt="Screenshot 2024-02-21 at 3 00 30 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/989fe086-66d0-4fa8-9a8c-13ad1d8b14b4">

## What I expected to happen

The buttons below the radio options should be clickable. 

## Reproducing
- Formation version: Not sure
- Device: Macbook Pro
- Browser: Chrome (latest)

Steps to reproduce:

1. Go to the FSR form: https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction
2. Try adding a spouse's job: https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-question
4. Try clicking on the continue button

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details
Screenshot of issue:
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/965ee96f-cf05-4ee3-9826-fee32175f577)

Link to video in Slack of issue: https://dsva.slack.com/files/U02HWQYB8G1/F06L105612N/buttons-uswds.mp4

**Comment by Mottie** [comment] 2024-02-21 23:19
Duplicate of #2491, which has a fix merged in. Pending update of library to 37.0.0+ in vets-website

**Comment by caw310** [comment] 2024-02-22 18:22
Closing since this is a duplicate

**Closed by caw310** 2024-02-22 18:22 UTC
Labels: bug, platform-design-system-team
