### ISSUE TITLE
Experimental Design [Process List] - minor change or documentation request

### ISSUE THREAD

**Issue by jstrothman** [department-of-veterans-affairs/vets-design-system-documentation#1835] opened 2023-06-09 13:27 UTC
## What
This is a suggestion for a minor change to an existing component (process list) or to its documentation, perhaps for consideration in #1737
(The implementation in the storybook instance and the example instance in production vary--I'm not sure if there's an intended consistent computed distance to the left edge of the container.)

## Purpose
Provide longer line length on small screens to increase readability, particularly for lists within process list items. Suggestion: use same distance as USWDS.

## Usage
No suggested change of usage from [current component usage guidance](https://design.va.gov/components/process-list#usage)

## Behavior
The computed distance from the process list number (not surrounding circle) to the left side of the container varies in the design system examples and on production. The USWDS uses no effective distance at all. 

1. 60px - Computed distance from left side of container in [va-process-list in storybook](https://design.va.gov/storybook/?path=/docs/components-va-process-list--default)
2. 60px - Computed distance from left side of container on [production Request Board Appeal page](https://www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction)
3. 23px - The [VA Design System process list page](https://design.va.gov/components/process-list) shows an `instance in production` ([Change your Education Benefits](https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction)) with less computed distance than the storybook example
4. 16px - [USWDS component page](https://designsystem.digital.gov/components/process-list)

## Examples
Request Board Appeal on production xsmall-screen (same distance as va-process-list in storybook)
![board appeal xsmall-screen](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1080991/873a387b-bbf2-4162-8c4b-38c88a557aeb)

USWDS component xsmall-screen
![uswds component xsmall-screen](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1080991/21bcfce5-c964-467f-8077-288b45ceef38)

## Next steps
This could be an asynchronous review by the Design System Council.

**Comment by eileen-coforma** [comment] 2023-06-09 18:05
Here is a screenshot from a screenshare that a Veteran on a mobile phone from one of our research sessions. The issue is exacerbated if the Veteran uses any type of screen zoom.

![Screenshot 2023-06-09 at 2 04 14 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/111457818/ee6c5acb-d936-4ed8-8335-fdf5a352e912)

**Comment by caw310** [comment] 2023-06-13 13:49
@jstrothman , Your experimental design request is on the agenda for the Design System Council meeting on Friday, June 16 at 1pm ET. Are you able to attend to discuss?  Thanks.

**Comment by humancompanion-usds** [comment] 2023-06-16 17:56
We decided in DSC today to make the alteration to the existing component to make it match the USWDS component in left-margin (and other spacing if necessary) to smooth the transition to the v3 version of this component.

**Comment by caw310** [comment] 2023-06-16 17:57
We will make change to existing component and then make v3 available once it is ready. DST will add this work to an upcoming sprint.

**Comment by humancompanion-usds** [comment] 2024-01-10 21:58
This is fixed in v3 which is now available to all teams. Annoyingly, we did not do what we said we'd do and fix it in v1. But we're far enough along on moving to v3 that I think it's spilt milk and we should just encourage teams to move to the v3 variation.

![Screenshot 2024-01-10 at 4 57 36 PM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/52176351/1eeb5b8d-3e09-4118-8250-659d5534c5f6)

**Closed by humancompanion-usds** 2024-01-10 21:58 UTC
Labels: platform-design-system-team, experimental_design, DSC request, va-process-list
