### ISSUE TITLE
Tag component should use USWDS v3 background color

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/vets-design-system-documentation#2361] opened 2024-01-03 21:23 UTC
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

In both Figma and in Storybook the Tag component background-color gray does not match the USWDS v3 color. 

* USWDS v3: #5c5c5c or gray-60
* Storybook: #5b616b
* Figma: #565c65 or vads-color-gray

## What I expected to happen

I expect us to align on the USWDS v3 color and update the component in Figma and Storybook appropriately.

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

### Details

I think we just overlooked that this component should be aligned with USWDSv3. Dan or Lucas should have a look to be sure that the entire component is synced with the USWDS version. Look at padding, border radius, font-size, line-height, etc.

**Comment by caw310** [comment] 2024-01-25 15:03
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2361?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by Andrew565** [comment] 2024-01-26 16:35
I'll tackle the developer side of the equation.

**Comment by Andrew565** [comment] 2024-01-26 16:39
Confirmed that this is already fixed in storybook as of today, turning back over to designers.

**Comment by danbrady** [comment] 2024-01-26 17:32
This will probably need more research but here's what I've discovered so far:

- In Figma, our Tag component background uses `vads-color-gray` variable which maps to `uswds-system-color-gray-cool-60` which is `#565c65`. This is how `vads-color-gray` is specified in [Airtable](https://airtable.com/appF4FJKBeNVNGrlm/tblVoDslTYpAh7dr1/viw5VK18YcZe6E4vq?blocks=hide).

- If you [look at the code](https://github.com/uswds/uswds/blob/202448875393d39d663614d2d8f9a12c91fed75e/packages/usa-tag/src/styles/_usa-tag.scss#L7) for the USWDS Tag component, it's background color uses `base-dark` token which maps to `theme-color-base-dark`  which also renders to `#565c65`. ([Link to USWDS tokens](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)).

- However, if you inspect the USDWS tag on their doc site, you'll see the background color is coming through as `#5c5c5c`! I believe their doc site is using an [older color theme](https://github.com/uswds/uswds-site/blob/8358991588381210f51afedfef8a527b46108a4f/css/settings/_uswds-theme-color.scss#L32) (shows 2.0.0 Beta 6 in header comments). 
![image](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/381190/c695176d-e881-45a8-aa42-601e05ff7f15)

**Comment by danbrady** [comment] 2024-05-03 14:16
@humancompanion-usds Since we're modifiying this component in design and code, do we want to bring in [USWDS Big tag](https://designsystem.digital.gov/components/tag/) variation as well?

**Closed** 2024-05-17 14:32 UTC
Labels: bug, platform-design-system-team, va-tag, Figma

**Comment by humancompanion-usds** [comment] 2024-05-20 14:54
@danbrady - We don't have a use case for Big tag yet. We could put it on the backlog but it isn't a priority.
